### PR TITLE
create order table

### LINKED ISSUE #46: Create Orders Table
### Context
This module should create an ``Orders`` table 

### Process
- Write a function that drops the ``Orders`` table if it already exists
- Write a function that creates the ``Orders `` table if it doesn't already exist
- Insert the appropriate data into the table
- Export the function

### Expected Result
When the function is called in ``build-db.js``, it should create a table in the database with the data from the json files.

### LINKED ISSUE #66: Create Orders Table
### Context
This should create the model to fetch data from the ``Orders`` table

### Associated Product Ticket
Issue #4 

### Process
1. Create a function that promises to GET all orders
1. Create a function that promises to GET an order
1. Create a function that promises to POST an order
1. Create a function that promises to PUT an order

### Expected Result
This module should export the above functions

### PR DESCRIPTION
**Pull request by kenziebottoms**
# Description
Add createOrderTable to `npm run db:generate`

## Related Ticket(s)
fixes #46, fixes #66

## Steps to Test Solution

1. `npm run db:generate`
2. There should now be an `orders` table.

### CODE REVIEW

**Comment by DavidLarsKetch** [comment]
Testing

**Review by TimAConner — DISMISSED** [review]
Throws this error when I run `npm run db:generate` since the escaping a single quote has not been pulled in from master.
```
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_ERROR: near "Conner": syntax error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bangazon-api-sprint1@1.0.0 db:generate: `node db/build-db.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bangazon-api-sprint1@1.0.0 db:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tim\AppData\Roaming\npm-cache\_logs\2018-03-22T16_48_01_589Z-debug.log
```

**Review by jordan-castelloe — APPROVED** [review]
looks good!

**Review by DavidLarsKetch — APPROVED** [review]
:+1:

**Pull request merged**
