### PR TITLE
orders: put/post => update

### PR DESCRIPTION
**Pull request by kenziebottoms**
# Description
`PUT` and `POST` now use the same model and controller functions.

## Related Ticket(s)
#103 

## Steps to Test Solution
1. `npm run db:generate`
1. `npm start`
1. Make a `POST` request to route root (`/employees`, `/customers`, etc.)
1. Make a `PUT` request to an existing ID
1. Make a `PUT` request to an ID that doesn't have an object (use ID 100 because you know that won't be in use)
1. Check that all requests do what you expect them to.
1. All requests should return the ID of the updated/created object

### CODE REVIEW

**Review by TimAConner — CHANGES_REQUESTED** [review]
Code in here will conflict with master.  Merge first.

**Review by TimAConner — APPROVED** [review]
Works!

**Comment by jordan-castelloe** [comment]
Testing!

**Review by jordan-castelloe — APPROVED** [review]
It works!

**Pull request merged**
