### PR TITLE
added a way to randomize payment types for our payment options

### PR DESCRIPTION
**Pull request by joechesney**
# Description
This adds a small function to generate random paymentTypes for each paymentOption.

## Number of Fixes
1

## Related Ticket(s)
#75 

## Problem to Solve
Faker did not give us a method to generate payment types such as "Visa", "Mastercard".

## Expected Behavior
When you run `node data/build-db.js`, it will give you some nice payment types

## Steps to Test Solution

1. run `node data/build-db.js`, and look at the json file for paymentOptions and look at the `type` property for each payment option object.

### CODE REVIEW

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
pls upload `json` file! good job!

**Review by DavidLarsKetch — APPROVED** [review]
:+1:

**Review by TimAConner — CHANGES_REQUESTED** [review]
Please change " to `.

**Review by kenziebottoms — APPROVED** [review]

**Review by jordan-castelloe — APPROVED** [review]
Woohoo! Looks good!

**Pull request merged**
