### PR TITLE
Fixes #86: Error handling & status codes

### LINKED ISSUE #86: Set-up app.js for receiving routes, handling errors
### Context
1. `app.js` receives all routes from `routes/index.js` & prepends the `URL` path to whatever we specify
1. `app.js` catches all errors thrown in `controllers` and sends back `404` errors

### Process
1. Without this, routes will/may not run properly since `app.js` is, you know, _the app_
2. Without error handling, we will be terrible programmers. Here's a _non-exhaustive_ list of errors to handle:
  - `404`: request made does not exist
  - `500`: the app/database broke
3. All `controllers` should call `next(err)` when an `Error` is thrown 

### Expected Result
Starting up the app (`node app.js`) & navigating to a completed MVC route in the browser, should return the requested data. Navigating to an _incomplete_ MVC route or _nonexistent_ route should return the appropriate error.

### PR DESCRIPTION
**Pull request by DavidLarsKetch**
# Description
Provides error handling in `app.js` and in `controllers`, supplying appropriate status codes for requests

## Number of Fixes
1

## Related Ticket(s)
Fixes #86 
Waiting on #107 - cannot properly handle errors with `DELETE` until this issue is closed

## Problem to Solve
Previously, we did not have a consistent way of handling errors, or in providing informative status codes about requests.

## Proposed Changes
1. `app.js` has a catch-all error handler that receives `next(err)` from the `controllers`, sending the status code and error message to the client (if received from a `controller`) and otherwise sends `500: Internal Server Error`.
1. For `GET` requests, if _no data is available_ at the requested spot - whether all the data in a table or at a specific `id` - controllers return `204`
  1. We return `204` instead of `404` because there may not necessarily be data at the requested spot in the future
1. For `POST` & `PUT` functions, it returns `400` if the user did not send in the required parameters

## Expected Behavior
1. A `GET` call to a table that _does_ exist, but doesn't have the particular resource requested, returns `204`. E.g. `computers/34023` when there is no `computer_id = 34023` returns `204`
1. A `POST` or `PUT` call to a table that doesn't have the required parameters returns `400` & message with the required parameters. E.g., `POST` `computers/` with `{ "some": "random", "data": "man" }` returns `400` and `{ error: "Please include: purchase_date and decomission_date" }`.
1. Querying a `URL` path that doesn't exist returns `404`
1. Internal Server Errors return `500`

## Steps to Test Solution

1.  `npm run db:generate`

2. In your DB browser run: `DELETE FROM Computers`

3. `npm start`

4. [http://localhost:8080/api/v1/computers](http://localhost:8080/api/v1/computers) should return `204`

5. [http://localhost:8080/api/v1/computers/52](http://localhost:8080/api/v1/computers/52) should return `204`

6. `POST` `http://localhost:8080/api/v1/orders/`, this payload:
  ```
  {
    "something": "random"
  }
  ```
  Should return `400` and `{ error: "Please include: customer_id and payment_type_id" }`
 
7. `PUT` `http://localhost:8080/api/v1/orders/2`, this payload:
  ```
  {
    "something": "random"
  }
  ```
  Should return `400` and `{ error: "Please include: customer_id and payment_type_id" }`

## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[x] I certify that all existing tests pass

### CODE REVIEW

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
check `data.length >= 1` instead of `data >= 1` in ctrls

**Review by kenziebottoms — APPROVED** [review]

**Review by TimAConner — CHANGES_REQUESTED** [review]
After running `DELETE FROM Departments`, departments/1 returns a 500 while it should return 204.
products/1 returns 204 even if it does exist.

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
Can't get individual objects (`/products/1`, `/computers/8`, etc.)

**Comment by jordan-castelloe** [comment]
Testing again!

**Review by kenziebottoms — APPROVED** [review]

**Review by jordan-castelloe — APPROVED** [review]
Looks good!

**Pull request merged**
