### PR TITLE
Updates package.json & app.js to use body-parser

### PR DESCRIPTION
**Pull request by DavidLarsKetch**
# Description
Updates `app.js` so we don't have merge conflicts with the extra `HTTP` verbs we're working on.

## Number of Fixes
N/A

## Related Ticket(s)
#86 

## Problem to Solve
A middleware solution was needed to get data from requests into proper `JSON` format

## Proposed Changes
**Prepends `api/v1` to all `URL` paths.**
Gives access to `body-parser` middleware for `POST`, `PUT`, etc. verbs

## Expected Behavior
`body-parser` gets our data into `JSON` format for the sake of those `HTTP` calls we're making

## Steps to Test Solution

1. `git merge [your-branch] dlk-app-update`
1. `npm install`
1. Write a `PUT` or `POST` function in the feature you're working on

### CODE REVIEW

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
Spell require right :nerd_face: 
```js
const bodyParser = require('body-parser');
```

**Review by joechesney — APPROVED** [review]
you spelled require wrong, you jabroni

**Review by joechesney — CHANGES_REQUESTED** [review]
require is spelled wrong

do i need to say "you had one job" here?

**Comment by DavidLarsKetch** [comment]
lol

**Comment by DavidLarsKetch** [comment]
hit the wrong button

**Comment by DavidLarsKetch** [comment]
OK, ready

**Comment by jordan-castelloe** [comment]
testing!

**Review by kenziebottoms — APPROVED** [review]

**Review by jordan-castelloe — APPROVED** [review]
Everything is spelled so right.

**Pull request merged**
