### PR TITLE
all methods on /computers endpoints

### LINKED ISSUE #8: Allow developers to access the Computer resource
Verbs to be supported

- [x] GET
- [x] POST
- [x] PUT
- [x] DELETE

User should be able to GET a list, and GET a single item.

### LINKED ISSUE #56: Create Computers MVC
### Context
This should create the model, route, and controller to fetch data from the Computers table.

### Associated Product Ticket
Issue #2 

### Process
1. Create a function that promises to GET all products
1. Create a function that promises to GET a single product
1. Create a function that promises to POST a product
1. Create a function that promises to PUT a product
1. Create a function that promises to DELETE a product

### Expected Result
This module should export the above functions

### PR DESCRIPTION
**Pull request by kenziebottoms**
# Description
Establishes the following endpoints:
- `GET /computers`: get all computres
- `GET /computers/:id`: get one computer by id
- `POST /computers`: post new computer
- `PUT /computers/:id`: update one computer by id
- `DELETE /computers/:id`: delete one computer by id

## Related Ticket(s)
fixes #56, extends #88, fixes #8 

## Steps to Test Solution
1. `git checkout kb-computer-post`
1. `npm install`
1. comment out non-computer routes
1. `npm run db:generate`
1. `npm start`
1. http://localhost:8080/api/v1/computers should give you 25 computers
1. http://localhost:8080/api/v1/computers/20 should give you
  ```js
  {
  computer_id: 20,
  mac_address: "42:c6:54:a1:77:3d",
  purchase_date: "2016-04-06T01:32:38.272Z",
  decommission_date: "2017-11-10T14:25:59.680Z"
  }
  ```
1. open Postman or whatever and `POST localhost:8080/api/v1/computers`
  ```json
  { "mac_address": "hello",
  "purchase_date": "my name is",
  "decommission_date": "inigo montoya" }
  ```
1. http://localhost:8080/api/v1/computers/25 should now show the above JSON
1. open Postman or whatever and `PUT http://localhost:8080/api/v1/computers/20`
  ```json
  { "mac_address": "hello",
  "purchase_date": "my name is",
  "decommission_date": "inigo montoya" }
  ```
1. http://localhost:8080/api/v1/computers/20 should now also show that JSON
1. open Postman or whatever and `DELETE localhost:8080/api/v1/computers/25`
1. http://localhost:8080/api/v1/computers/25 should now give you a "Computer not found." error

### CODE REVIEW

**Comment by DavidLarsKetch** [comment]
testing

**Comment by jordan-castelloe** [comment]
testing!

**Review by jordan-castelloe — APPROVED** [review]
APPROVED. LOTS OF APPROVAL. HIGH APPROVAL RATINGS.

**Comment by DavidLarsKetch** [comment]
I failed

**Review by TimAConner — APPROVED** [review]
Fine and Dandy.

**Pull request merged**
