### PR TITLE
fixes issue #22 creates controller files

### PR DESCRIPTION
**Pull request by joechesney**
# Description
This pull request creates the controller files for the entire project. Each controller file requires in the corresponding Model file, and has a line that exports the controllers functions. There is nothing else currently in the controller files.

## Number of Fixes
1 Fix

## Related Ticket(s)
Issue #22 - Initialize Controllers

## Problem to Solve
We needed controllers and now we have them.

## Proposed Changes
All I did was add the controller files

## Expected Behavior
The controller files exist

## Steps to Test Solution

1. Look in the root of the project for a folder called controllers. That folder should contain 2 folders called Employees and Products. Those folders should contain controller files that pertain to the name of the folder they are in.

## Testing

[ ] There are new unit tests in this PR, and I verify that there is full coverage of all new code.
[ ] I certify that all existing tests pass

## Documentation
[ ] There is new documentation in this pull request that must be reviewed..
[ ] I added documentation for any new classes/methods

## Deploy Notes
Everyone should pull down the new master after this is merged, so that we will all have the controller files.

### CODE REVIEW

**Review by jordan-castelloe — COMMENTED** [review]
Add productOrderCtrl.js! Other than that it looks grovy

**Comment by DavidLarsKetch** [comment]
Export that shi - each controller needs `module.exports = {}`

**Review by DavidLarsKetch — CHANGES_REQUESTED** [review]
Export that shi - each controller needs `module.exports = {}`

**Review by jordan-castelloe — APPROVED** [review]
Looks good!

**Review by DavidLarsKetch — APPROVED** [review]
:+1:

**Pull request merged**
