### PR TITLE
fixed routes so that the section prefix is in the index file of that …

### LINKED ISSUE #109: Follow Kenzie's dope approach to routes
### Context
1. @kenziebottoms came up with a way of writing routes that we should follow because it looks clean & clear.
2. This should be applied `routes/products/index` & `routes/employees/index` and each `route` in `routes/products/` & `routes/employees/`

### Process
1. The `indexRouter.use(...)` statements in `employees/index` & `products/index` should include the table name.
1. The `URL` path `routes.[VERB]` in each individual route should only be `('/', [function])` or `('/:id', [function])`

### Expected Result
Each `route.use` should look like `route.use('/[table-name]', require('/[table-name]'));`

### PR DESCRIPTION
**Pull request by joechesney**
…folder, rather than in the individual routes files

# Description
Changed routes so that the section (table) prefix is in the index file of that folder, rather than in the individual routes files.

## Number of Fixes
Type of number of fixes included in this PR.

## Related Ticket(s)
Fixes #109 

## Problem to Solve
Makes individual routes  a little easier to read because the route prefix is in the index file rather than at the beginning of the route in each route file.

## Expected Behavior
All routes should hopefully still work. Without testing each individual route, we can just scour this pull requests code changes and make DANG sure that each route is still properly routed.

## Steps to Test Solution

1. Read through every single file of this pull request, and make sure that each route is still intact. 
2. Test every single route.

### CODE REVIEW

**Comment by kenziebottoms** [comment]
testing

**Review by kenziebottoms — CHANGES_REQUESTED** [review]
Can we just remove `/routes/employees/index.js:10-11`? Otherwise good!

**Review by kenziebottoms — APPROVED** [review]

**Comment by jordan-castelloe** [comment]
testing!

**Review by jordan-castelloe — APPROVED** [review]
Looks good!

**Pull request merged**
